- hosts: frontends
  become: yes
  roles:
   - common
   - lb

- hosts: apps
  become: yes
  roles:
   - common
   - app-tier

- hosts: appdbs
  become: yes
  roles:
   - common
   - geerlingguy.postgresql

